
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    # Uncomment and modify the following if you need environment variables
    # environment:
    #   - NODE_ENV=production

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "81:8080"
    environment:
      - JENKINS_OPTS="--httpPort=8082"
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=password
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins_home:
